---

- name: MONGODB | Ensure MongoDb service is started
  systemd:
    name: mongod
    state: restarted

- name: MONGODB | Deploy MongoDb replication set script
  template:
    src: "opt/mongodb/repset_init.js.j2"
    dest: "{{ mongodb_directory }}/repset_init.js"
    owner: mongodb
    group: mongodb
    mode: 0644

- name: MONGODB | Initialize the replication set
  shell: /usr/bin/mongo {{ mongodb_directory }}/repset_init.js
  run_once: yes
